<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../pkvault-src/PKVault.Core/PKVault.Core.csproj" />
    <Reference Include="PKHeX.Core">
      <HintPath>../../pkvault-src/PKVault.Core/PKHeX.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
